/* eslint-disable camelcase */
export interface IFollower {
  login: string;
  id: number;
  node_id: string;
  avatar_url: string;
  gravatar_id: string;
  url: string;
  html_url: string;
  followers_url: string;
  following_url: string;
  gists_url: string;
  starred_url: string;
  subscriptions_url: string;
  organizations_url: string;
  repos_url: string;
  events_url: string;
  received_events_url: string;
  type: string;
  site_admin: boolean;
}

export default [
  {
    login: 'jeycin',
    id: 1809948,
    node_id: 'MDQ6VXNlcjE4MDk5NDg=',
    avatar_url: 'https://avatars.githubusercontent.com/u/1809948?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/jeycin',
    html_url: 'https://github.com/jeycin',
    followers_url: 'https://api.github.com/users/jeycin/followers',
    following_url: 'https://api.github.com/users/jeycin/following{/other_user}',
    gists_url: 'https://api.github.com/users/jeycin/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/jeycin/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/jeycin/subscriptions',
    organizations_url: 'https://api.github.com/users/jeycin/orgs',
    repos_url: 'https://api.github.com/users/jeycin/repos',
    events_url: 'https://api.github.com/users/jeycin/events{/privacy}',
    received_events_url: 'https://api.github.com/users/jeycin/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'neshaug',
    id: 90493,
    node_id: 'MDQ6VXNlcjkwNDkz',
    avatar_url: 'https://avatars.githubusercontent.com/u/90493?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/neshaug',
    html_url: 'https://github.com/neshaug',
    followers_url: 'https://api.github.com/users/neshaug/followers',
    following_url:
      'https://api.github.com/users/neshaug/following{/other_user}',
    gists_url: 'https://api.github.com/users/neshaug/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/neshaug/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/neshaug/subscriptions',
    organizations_url: 'https://api.github.com/users/neshaug/orgs',
    repos_url: 'https://api.github.com/users/neshaug/repos',
    events_url: 'https://api.github.com/users/neshaug/events{/privacy}',
    received_events_url: 'https://api.github.com/users/neshaug/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'seanlin',
    id: 139739,
    node_id: 'MDQ6VXNlcjEzOTczOQ==',
    avatar_url: 'https://avatars.githubusercontent.com/u/139739?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/seanlin',
    html_url: 'https://github.com/seanlin',
    followers_url: 'https://api.github.com/users/seanlin/followers',
    following_url:
      'https://api.github.com/users/seanlin/following{/other_user}',
    gists_url: 'https://api.github.com/users/seanlin/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/seanlin/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/seanlin/subscriptions',
    organizations_url: 'https://api.github.com/users/seanlin/orgs',
    repos_url: 'https://api.github.com/users/seanlin/repos',
    events_url: 'https://api.github.com/users/seanlin/events{/privacy}',
    received_events_url: 'https://api.github.com/users/seanlin/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'alvesjnr',
    id: 227336,
    node_id: 'MDQ6VXNlcjIyNzMzNg==',
    avatar_url: 'https://avatars.githubusercontent.com/u/227336?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/alvesjnr',
    html_url: 'https://github.com/alvesjnr',
    followers_url: 'https://api.github.com/users/alvesjnr/followers',
    following_url:
      'https://api.github.com/users/alvesjnr/following{/other_user}',
    gists_url: 'https://api.github.com/users/alvesjnr/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/alvesjnr/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/alvesjnr/subscriptions',
    organizations_url: 'https://api.github.com/users/alvesjnr/orgs',
    repos_url: 'https://api.github.com/users/alvesjnr/repos',
    events_url: 'https://api.github.com/users/alvesjnr/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/alvesjnr/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'apburton84',
    id: 523372,
    node_id: 'MDQ6VXNlcjUyMzM3Mg==',
    avatar_url: 'https://avatars.githubusercontent.com/u/523372?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/apburton84',
    html_url: 'https://github.com/apburton84',
    followers_url: 'https://api.github.com/users/apburton84/followers',
    following_url:
      'https://api.github.com/users/apburton84/following{/other_user}',
    gists_url: 'https://api.github.com/users/apburton84/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/apburton84/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/apburton84/subscriptions',
    organizations_url: 'https://api.github.com/users/apburton84/orgs',
    repos_url: 'https://api.github.com/users/apburton84/repos',
    events_url: 'https://api.github.com/users/apburton84/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/apburton84/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'prudhviy',
    id: 562138,
    node_id: 'MDQ6VXNlcjU2MjEzOA==',
    avatar_url: 'https://avatars.githubusercontent.com/u/562138?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/prudhviy',
    html_url: 'https://github.com/prudhviy',
    followers_url: 'https://api.github.com/users/prudhviy/followers',
    following_url:
      'https://api.github.com/users/prudhviy/following{/other_user}',
    gists_url: 'https://api.github.com/users/prudhviy/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/prudhviy/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/prudhviy/subscriptions',
    organizations_url: 'https://api.github.com/users/prudhviy/orgs',
    repos_url: 'https://api.github.com/users/prudhviy/repos',
    events_url: 'https://api.github.com/users/prudhviy/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/prudhviy/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'kanpan',
    id: 649458,
    node_id: 'MDQ6VXNlcjY0OTQ1OA==',
    avatar_url: 'https://avatars.githubusercontent.com/u/649458?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/kanpan',
    html_url: 'https://github.com/kanpan',
    followers_url: 'https://api.github.com/users/kanpan/followers',
    following_url: 'https://api.github.com/users/kanpan/following{/other_user}',
    gists_url: 'https://api.github.com/users/kanpan/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/kanpan/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/kanpan/subscriptions',
    organizations_url: 'https://api.github.com/users/kanpan/orgs',
    repos_url: 'https://api.github.com/users/kanpan/repos',
    events_url: 'https://api.github.com/users/kanpan/events{/privacy}',
    received_events_url: 'https://api.github.com/users/kanpan/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'ccchow',
    id: 676657,
    node_id: 'MDQ6VXNlcjY3NjY1Nw==',
    avatar_url: 'https://avatars.githubusercontent.com/u/676657?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/ccchow',
    html_url: 'https://github.com/ccchow',
    followers_url: 'https://api.github.com/users/ccchow/followers',
    following_url: 'https://api.github.com/users/ccchow/following{/other_user}',
    gists_url: 'https://api.github.com/users/ccchow/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/ccchow/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/ccchow/subscriptions',
    organizations_url: 'https://api.github.com/users/ccchow/orgs',
    repos_url: 'https://api.github.com/users/ccchow/repos',
    events_url: 'https://api.github.com/users/ccchow/events{/privacy}',
    received_events_url: 'https://api.github.com/users/ccchow/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'scottdnz',
    id: 700396,
    node_id: 'MDQ6VXNlcjcwMDM5Ng==',
    avatar_url: 'https://avatars.githubusercontent.com/u/700396?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/scottdnz',
    html_url: 'https://github.com/scottdnz',
    followers_url: 'https://api.github.com/users/scottdnz/followers',
    following_url:
      'https://api.github.com/users/scottdnz/following{/other_user}',
    gists_url: 'https://api.github.com/users/scottdnz/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/scottdnz/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/scottdnz/subscriptions',
    organizations_url: 'https://api.github.com/users/scottdnz/orgs',
    repos_url: 'https://api.github.com/users/scottdnz/repos',
    events_url: 'https://api.github.com/users/scottdnz/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/scottdnz/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'johnaohara',
    id: 959822,
    node_id: 'MDQ6VXNlcjk1OTgyMg==',
    avatar_url: 'https://avatars.githubusercontent.com/u/959822?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/johnaohara',
    html_url: 'https://github.com/johnaohara',
    followers_url: 'https://api.github.com/users/johnaohara/followers',
    following_url:
      'https://api.github.com/users/johnaohara/following{/other_user}',
    gists_url: 'https://api.github.com/users/johnaohara/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/johnaohara/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/johnaohara/subscriptions',
    organizations_url: 'https://api.github.com/users/johnaohara/orgs',
    repos_url: 'https://api.github.com/users/johnaohara/repos',
    events_url: 'https://api.github.com/users/johnaohara/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/johnaohara/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'cable729',
    id: 1524578,
    node_id: 'MDQ6VXNlcjE1MjQ1Nzg=',
    avatar_url: 'https://avatars.githubusercontent.com/u/1524578?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/cable729',
    html_url: 'https://github.com/cable729',
    followers_url: 'https://api.github.com/users/cable729/followers',
    following_url:
      'https://api.github.com/users/cable729/following{/other_user}',
    gists_url: 'https://api.github.com/users/cable729/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/cable729/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/cable729/subscriptions',
    organizations_url: 'https://api.github.com/users/cable729/orgs',
    repos_url: 'https://api.github.com/users/cable729/repos',
    events_url: 'https://api.github.com/users/cable729/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/cable729/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'seanevocorde',
    id: 1564925,
    node_id: 'MDQ6VXNlcjE1NjQ5MjU=',
    avatar_url: 'https://avatars.githubusercontent.com/u/1564925?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/seanevocorde',
    html_url: 'https://github.com/seanevocorde',
    followers_url: 'https://api.github.com/users/seanevocorde/followers',
    following_url:
      'https://api.github.com/users/seanevocorde/following{/other_user}',
    gists_url: 'https://api.github.com/users/seanevocorde/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/seanevocorde/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/seanevocorde/subscriptions',
    organizations_url: 'https://api.github.com/users/seanevocorde/orgs',
    repos_url: 'https://api.github.com/users/seanevocorde/repos',
    events_url: 'https://api.github.com/users/seanevocorde/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/seanevocorde/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'daryltucker',
    id: 1609490,
    node_id: 'MDQ6VXNlcjE2MDk0OTA=',
    avatar_url: 'https://avatars.githubusercontent.com/u/1609490?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/daryltucker',
    html_url: 'https://github.com/daryltucker',
    followers_url: 'https://api.github.com/users/daryltucker/followers',
    following_url:
      'https://api.github.com/users/daryltucker/following{/other_user}',
    gists_url: 'https://api.github.com/users/daryltucker/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/daryltucker/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/daryltucker/subscriptions',
    organizations_url: 'https://api.github.com/users/daryltucker/orgs',
    repos_url: 'https://api.github.com/users/daryltucker/repos',
    events_url: 'https://api.github.com/users/daryltucker/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/daryltucker/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'merencia',
    id: 1686635,
    node_id: 'MDQ6VXNlcjE2ODY2MzU=',
    avatar_url: 'https://avatars.githubusercontent.com/u/1686635?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/merencia',
    html_url: 'https://github.com/merencia',
    followers_url: 'https://api.github.com/users/merencia/followers',
    following_url:
      'https://api.github.com/users/merencia/following{/other_user}',
    gists_url: 'https://api.github.com/users/merencia/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/merencia/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/merencia/subscriptions',
    organizations_url: 'https://api.github.com/users/merencia/orgs',
    repos_url: 'https://api.github.com/users/merencia/repos',
    events_url: 'https://api.github.com/users/merencia/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/merencia/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'luoyangylh',
    id: 1758102,
    node_id: 'MDQ6VXNlcjE3NTgxMDI=',
    avatar_url: 'https://avatars.githubusercontent.com/u/1758102?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/luoyangylh',
    html_url: 'https://github.com/luoyangylh',
    followers_url: 'https://api.github.com/users/luoyangylh/followers',
    following_url:
      'https://api.github.com/users/luoyangylh/following{/other_user}',
    gists_url: 'https://api.github.com/users/luoyangylh/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/luoyangylh/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/luoyangylh/subscriptions',
    organizations_url: 'https://api.github.com/users/luoyangylh/orgs',
    repos_url: 'https://api.github.com/users/luoyangylh/repos',
    events_url: 'https://api.github.com/users/luoyangylh/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/luoyangylh/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'sinisbad123',
    id: 1787177,
    node_id: 'MDQ6VXNlcjE3ODcxNzc=',
    avatar_url: 'https://avatars.githubusercontent.com/u/1787177?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/sinisbad123',
    html_url: 'https://github.com/sinisbad123',
    followers_url: 'https://api.github.com/users/sinisbad123/followers',
    following_url:
      'https://api.github.com/users/sinisbad123/following{/other_user}',
    gists_url: 'https://api.github.com/users/sinisbad123/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/sinisbad123/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/sinisbad123/subscriptions',
    organizations_url: 'https://api.github.com/users/sinisbad123/orgs',
    repos_url: 'https://api.github.com/users/sinisbad123/repos',
    events_url: 'https://api.github.com/users/sinisbad123/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/sinisbad123/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'ccotter',
    id: 1799998,
    node_id: 'MDQ6VXNlcjE3OTk5OTg=',
    avatar_url: 'https://avatars.githubusercontent.com/u/1799998?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/ccotter',
    html_url: 'https://github.com/ccotter',
    followers_url: 'https://api.github.com/users/ccotter/followers',
    following_url:
      'https://api.github.com/users/ccotter/following{/other_user}',
    gists_url: 'https://api.github.com/users/ccotter/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/ccotter/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/ccotter/subscriptions',
    organizations_url: 'https://api.github.com/users/ccotter/orgs',
    repos_url: 'https://api.github.com/users/ccotter/repos',
    events_url: 'https://api.github.com/users/ccotter/events{/privacy}',
    received_events_url: 'https://api.github.com/users/ccotter/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'garvinwang',
    id: 1821348,
    node_id: 'MDQ6VXNlcjE4MjEzNDg=',
    avatar_url: 'https://avatars.githubusercontent.com/u/1821348?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/garvinwang',
    html_url: 'https://github.com/garvinwang',
    followers_url: 'https://api.github.com/users/garvinwang/followers',
    following_url:
      'https://api.github.com/users/garvinwang/following{/other_user}',
    gists_url: 'https://api.github.com/users/garvinwang/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/garvinwang/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/garvinwang/subscriptions',
    organizations_url: 'https://api.github.com/users/garvinwang/orgs',
    repos_url: 'https://api.github.com/users/garvinwang/repos',
    events_url: 'https://api.github.com/users/garvinwang/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/garvinwang/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'krishbandaru',
    id: 1864309,
    node_id: 'MDQ6VXNlcjE4NjQzMDk=',
    avatar_url: 'https://avatars.githubusercontent.com/u/1864309?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/krishbandaru',
    html_url: 'https://github.com/krishbandaru',
    followers_url: 'https://api.github.com/users/krishbandaru/followers',
    following_url:
      'https://api.github.com/users/krishbandaru/following{/other_user}',
    gists_url: 'https://api.github.com/users/krishbandaru/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/krishbandaru/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/krishbandaru/subscriptions',
    organizations_url: 'https://api.github.com/users/krishbandaru/orgs',
    repos_url: 'https://api.github.com/users/krishbandaru/repos',
    events_url: 'https://api.github.com/users/krishbandaru/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/krishbandaru/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'CNpigCA',
    id: 1866348,
    node_id: 'MDQ6VXNlcjE4NjYzNDg=',
    avatar_url: 'https://avatars.githubusercontent.com/u/1866348?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/CNpigCA',
    html_url: 'https://github.com/CNpigCA',
    followers_url: 'https://api.github.com/users/CNpigCA/followers',
    following_url:
      'https://api.github.com/users/CNpigCA/following{/other_user}',
    gists_url: 'https://api.github.com/users/CNpigCA/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/CNpigCA/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/CNpigCA/subscriptions',
    organizations_url: 'https://api.github.com/users/CNpigCA/orgs',
    repos_url: 'https://api.github.com/users/CNpigCA/repos',
    events_url: 'https://api.github.com/users/CNpigCA/events{/privacy}',
    received_events_url: 'https://api.github.com/users/CNpigCA/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'regop',
    id: 1872198,
    node_id: 'MDQ6VXNlcjE4NzIxOTg=',
    avatar_url: 'https://avatars.githubusercontent.com/u/1872198?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/regop',
    html_url: 'https://github.com/regop',
    followers_url: 'https://api.github.com/users/regop/followers',
    following_url: 'https://api.github.com/users/regop/following{/other_user}',
    gists_url: 'https://api.github.com/users/regop/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/regop/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/regop/subscriptions',
    organizations_url: 'https://api.github.com/users/regop/orgs',
    repos_url: 'https://api.github.com/users/regop/repos',
    events_url: 'https://api.github.com/users/regop/events{/privacy}',
    received_events_url: 'https://api.github.com/users/regop/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'wifiguy',
    id: 1877830,
    node_id: 'MDQ6VXNlcjE4Nzc4MzA=',
    avatar_url: 'https://avatars.githubusercontent.com/u/1877830?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/wifiguy',
    html_url: 'https://github.com/wifiguy',
    followers_url: 'https://api.github.com/users/wifiguy/followers',
    following_url:
      'https://api.github.com/users/wifiguy/following{/other_user}',
    gists_url: 'https://api.github.com/users/wifiguy/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/wifiguy/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/wifiguy/subscriptions',
    organizations_url: 'https://api.github.com/users/wifiguy/orgs',
    repos_url: 'https://api.github.com/users/wifiguy/repos',
    events_url: 'https://api.github.com/users/wifiguy/events{/privacy}',
    received_events_url: 'https://api.github.com/users/wifiguy/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'johnborges',
    id: 1888122,
    node_id: 'MDQ6VXNlcjE4ODgxMjI=',
    avatar_url: 'https://avatars.githubusercontent.com/u/1888122?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/johnborges',
    html_url: 'https://github.com/johnborges',
    followers_url: 'https://api.github.com/users/johnborges/followers',
    following_url:
      'https://api.github.com/users/johnborges/following{/other_user}',
    gists_url: 'https://api.github.com/users/johnborges/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/johnborges/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/johnborges/subscriptions',
    organizations_url: 'https://api.github.com/users/johnborges/orgs',
    repos_url: 'https://api.github.com/users/johnborges/repos',
    events_url: 'https://api.github.com/users/johnborges/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/johnborges/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'rustamsh',
    id: 1893446,
    node_id: 'MDQ6VXNlcjE4OTM0NDY=',
    avatar_url: 'https://avatars.githubusercontent.com/u/1893446?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/rustamsh',
    html_url: 'https://github.com/rustamsh',
    followers_url: 'https://api.github.com/users/rustamsh/followers',
    following_url:
      'https://api.github.com/users/rustamsh/following{/other_user}',
    gists_url: 'https://api.github.com/users/rustamsh/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/rustamsh/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/rustamsh/subscriptions',
    organizations_url: 'https://api.github.com/users/rustamsh/orgs',
    repos_url: 'https://api.github.com/users/rustamsh/repos',
    events_url: 'https://api.github.com/users/rustamsh/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/rustamsh/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'chriswhocodes',
    id: 1898314,
    node_id: 'MDQ6VXNlcjE4OTgzMTQ=',
    avatar_url: 'https://avatars.githubusercontent.com/u/1898314?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/chriswhocodes',
    html_url: 'https://github.com/chriswhocodes',
    followers_url: 'https://api.github.com/users/chriswhocodes/followers',
    following_url:
      'https://api.github.com/users/chriswhocodes/following{/other_user}',
    gists_url: 'https://api.github.com/users/chriswhocodes/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/chriswhocodes/starred{/owner}{/repo}',
    subscriptions_url:
      'https://api.github.com/users/chriswhocodes/subscriptions',
    organizations_url: 'https://api.github.com/users/chriswhocodes/orgs',
    repos_url: 'https://api.github.com/users/chriswhocodes/repos',
    events_url: 'https://api.github.com/users/chriswhocodes/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/chriswhocodes/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 's-r-k',
    id: 1898524,
    node_id: 'MDQ6VXNlcjE4OTg1MjQ=',
    avatar_url: 'https://avatars.githubusercontent.com/u/1898524?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/s-r-k',
    html_url: 'https://github.com/s-r-k',
    followers_url: 'https://api.github.com/users/s-r-k/followers',
    following_url: 'https://api.github.com/users/s-r-k/following{/other_user}',
    gists_url: 'https://api.github.com/users/s-r-k/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/s-r-k/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/s-r-k/subscriptions',
    organizations_url: 'https://api.github.com/users/s-r-k/orgs',
    repos_url: 'https://api.github.com/users/s-r-k/repos',
    events_url: 'https://api.github.com/users/s-r-k/events{/privacy}',
    received_events_url: 'https://api.github.com/users/s-r-k/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'klcant',
    id: 1898583,
    node_id: 'MDQ6VXNlcjE4OTg1ODM=',
    avatar_url: 'https://avatars.githubusercontent.com/u/1898583?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/klcant',
    html_url: 'https://github.com/klcant',
    followers_url: 'https://api.github.com/users/klcant/followers',
    following_url: 'https://api.github.com/users/klcant/following{/other_user}',
    gists_url: 'https://api.github.com/users/klcant/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/klcant/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/klcant/subscriptions',
    organizations_url: 'https://api.github.com/users/klcant/orgs',
    repos_url: 'https://api.github.com/users/klcant/repos',
    events_url: 'https://api.github.com/users/klcant/events{/privacy}',
    received_events_url: 'https://api.github.com/users/klcant/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'sprsquish',
    id: 206,
    node_id: 'MDQ6VXNlcjIwNg==',
    avatar_url: 'https://avatars.githubusercontent.com/u/206?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/sprsquish',
    html_url: 'https://github.com/sprsquish',
    followers_url: 'https://api.github.com/users/sprsquish/followers',
    following_url:
      'https://api.github.com/users/sprsquish/following{/other_user}',
    gists_url: 'https://api.github.com/users/sprsquish/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/sprsquish/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/sprsquish/subscriptions',
    organizations_url: 'https://api.github.com/users/sprsquish/orgs',
    repos_url: 'https://api.github.com/users/sprsquish/repos',
    events_url: 'https://api.github.com/users/sprsquish/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/sprsquish/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'pius',
    id: 365,
    node_id: 'MDQ6VXNlcjM2NQ==',
    avatar_url: 'https://avatars.githubusercontent.com/u/365?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/pius',
    html_url: 'https://github.com/pius',
    followers_url: 'https://api.github.com/users/pius/followers',
    following_url: 'https://api.github.com/users/pius/following{/other_user}',
    gists_url: 'https://api.github.com/users/pius/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/pius/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/pius/subscriptions',
    organizations_url: 'https://api.github.com/users/pius/orgs',
    repos_url: 'https://api.github.com/users/pius/repos',
    events_url: 'https://api.github.com/users/pius/events{/privacy}',
    received_events_url: 'https://api.github.com/users/pius/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'crafterm',
    id: 397,
    node_id: 'MDQ6VXNlcjM5Nw==',
    avatar_url: 'https://avatars.githubusercontent.com/u/397?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/crafterm',
    html_url: 'https://github.com/crafterm',
    followers_url: 'https://api.github.com/users/crafterm/followers',
    following_url:
      'https://api.github.com/users/crafterm/following{/other_user}',
    gists_url: 'https://api.github.com/users/crafterm/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/crafterm/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/crafterm/subscriptions',
    organizations_url: 'https://api.github.com/users/crafterm/orgs',
    repos_url: 'https://api.github.com/users/crafterm/repos',
    events_url: 'https://api.github.com/users/crafterm/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/crafterm/received_events',
    type: 'User',
    site_admin: false,
  },
];
